### ISSUE TITLE
Firebase config revealed

### ISSUE THREAD

**Issue by jugurthakacimi** [GTAOnline-Mods/GTA-Weekly-Updates#1]
Your firebase configs shouldn't be revealed to anybody in the Github repo.
**Hide your firebase config params in a dotenv file**

**Comment by Dan6erbond** [comment]
Hey, thanks for reporting this issue. May I know where the config is revealed so I can fix that?

**Comment by jugurthakacimi** [comment]
It's clearly on your _src/Firebase/firebase.ts_ file, the firebase config object should be using env variables than writing it your apikey...etc in your file.
**Firebase Config should always be hidden from public view**

**Comment by Dan6erbond** [comment]
As shown [here](https://firebase.google.com/docs/web/setup) in the Firebase guide, configs can be public as they're exposed by nature of how front-end applications work. Firebase hosting offers no such thing as environment variables, and the `deploy` script needs to build a finished set of HTML, Js and CSS files to upload to the platform.
